# Generated by Django 5.0 on 2023-12-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='id_mont',
            new_name='id_month',
        ),
    ]
