# Generated by Django 5.0 on 2023-12-30 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.UUIDField(default=uuid.UUID('cbc168fd-6874-45f1-bbd8-f661bd5bd83a'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.UUIDField(default=uuid.UUID('e55619d4-1dd2-4ba6-b033-9e7f3bdb983f'), editable=False, unique=True),
        ),
    ]
