# Generated by Django 5.0 on 2023-12-31 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_id_transaction_alter_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.UUIDField(default=uuid.UUID('038fac85-c893-4b04-a30c-553a0a68f13f'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.UUIDField(default=uuid.UUID('c53d09e1-990a-4a4f-b5d8-5b8223619c66'), editable=False, unique=True),
        ),
    ]
